jobs:
  - &dummy-job
    containerfile: ./Containerfile
    output-name: "ttl.sh/dummy"
    output-tags: ["1h"]
    build-args: &dummy-args
      BASE_IMAGE: "fedora:latest"
      PKGS: "podman bubblewrap bash systemd nnn"
      TIME: "{{ nowTag }}"
    annotations:
      HELLO: world
    labels:
      MY: label
  - <<: *dummy-job
    build-args:
      <<: *dummy-args
      PKGS: "podman bubblewrap bash systemd nnn"
      TIME: "{{ nowTag }}"
