jobs:
  - &dummy-job
    containerfile: ./Containerfile
    output-name: "ttl.sh/dummy"
    output-tags: ["1h"]
    build-args: &dummy-args
      BASE_IMAGE: "fedora:latest"
      PKGS: >-
        {{ block "packages" . -}}
        podman
        bubblewrap
        bash
        nnn
        {{- end }}
      TIME: "{{ nowTag }}"
    annotations:
      HELLO: world
    labels:
      MY: label
  - <<: *dummy-job
    build-args:
      <<: *dummy-args
      PKGS: >-
        {{ template "packages" }}
        firefox
      TIME: "{{ nowTag }}"
