jobs:
  - &dummy-job
    containerfile: ./Containerfile
    output-name: "ttl.sh/dummy"
    output-tags: ["1h"]
    build-args:
      - aaa=ubuntu
  - <<: *dummy-job
    build-args:
      - bbb=bbb
  - <<: *dummy-job
    build-args:
      - BASE_IMAGE=fedora
