jobs:
  - &dummy-job
    containerfile: ./Containerfile
    output-name: "ttl.sh/dummy"
    output-tags: ["1h"]
    build-args:
      - &base-image { key: BASE_IMAGE, value: "fedora:latest" }
      - &pkgs { key: PKGS, value: "podman bubblewrap bash systemd nnn" }
      - { key: TIME, value: "{{ nowTag }}-2" }
  - <<: *dummy-job
    build-args:
      - *base-image
      - { key: TIME, value: "{{ nowTag }}-2" }
