jobs:
  - &dummy-job
    containerfile: ./Containerfile
    output-name: "ttl.sh/bazzite"
    output-tags: ["1h"]
    build-args:
      - BASE_IMAGE=ghcr.io/ublue-os/bazzite:latest
  - <<: *dummy-job
    build-args:
      - BASE_IMAGE=ghcr.io/ublue-os/bazzite-nvidia:latest
  - <<: *dummy-job
    build-args:
      - BASE_IMAGE=ghcr.io/ublue-os/bazzite-gnome:latest
  - <<: *dummy-job
    build-args:
      - BASE_IMAGE=ghcr.io/ublue-os/bazzite-gnome-nvidia:latest
